using Autodesk.Revit.UI.Selection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CreateStairDesign.Stair.Model
{
    public class StairModel
    {
        public double Daythang1 { get; set; }
        public double Daythang2 { get; set; }
        public double Daythang3 { get; set; }
        public double Daythang4 { get; set; }
        public double b1 { get; set; }
        public double b2 { get; set; }
        public double b3 { get; set; }
        public double h1 { get; set; }
        public double h3 { get; set; }
        public double RongThang12 { get; set; }
        public double RongThang3 { get; set; }
        public double off { get; set; }
        public double y2 { get; set; }
    }
}
